from apps.apps_router import command_route, get_autogenerated_help_message


def get_help_text():
    return get_autogenerated_help_message()


@command_route(commands=["/help"],
               args=["server", "req"],
               help_text="Узнать, какие команды умеет выполнять этот бот.")
def execute(server, req):
    server.send_message(req.user, get_help_text())
